version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/rust:1-1-bullseye
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: redis

volumes:
  redis-data: