name: Rust

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo zypper refresh && sudo zypper install -y gcc

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Run
      run: cargo run
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}